version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    ports:
       - "5430:5432"
    volumes:
      - ./postgres-install-extensions.sh:/docker-entrypoint-initdb.d/postgres-install-extensions.sh