# Generated by Django 4.0.3 on 2022-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limit')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
