# Generated by Django 4.0.4 on 2022-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_plan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rate_plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('base', 'Базовый'), ('professional', 'Профессиональный')], default='free', max_length=13, verbose_name='Rate plan'),
        ),
        migrations.DeleteModel(
            name='RatePlan',
        ),
    ]
