# Generated by Django 4.1.3 on 2022-11-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='discord_id',
        ),
    ]
