# Generated by Django 4.1.3 on 2022-11-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0002_remove_customuser_discord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_id',
            new_name='telegram_uid',
        ),
    ]
