# Generated by Django 4.1.3 on 2022-11-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='user_id',
            new_name='user',
        ),
    ]
